name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git diff >> README.md
      - run: git config --global mahaprasad.parida "actions@users.noreply.github.com"
      - run: git config --global mahaprasad.parida "README-bot"
      - run: git add -A
      - run: git commit -m "Update content" || git commit --allow-empty -m "Empty commit"
      - run: git push
